name: Develop

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Working Jar task
        run: ./gradlew releaseSourcesJar

      - name: Failing Jar task
        run: ./gradlew debugSourcesJar
